######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 5 16:11:37 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
