######################################################################
# Automatically generated by qmake (3.0) Thu Oct 11 11:46:32 2018
######################################################################

TEMPLATE = lib
TARGET = simpleSharedLibrary
INCLUDEPATH += include
QT += gui widgets

# Input
SOURCES += src/MyMainWindow.cpp
