######################################################################
# Automatically generated by qmake (3.0) Thu Oct 11 10:59:18 2018
######################################################################

TEMPLATE = app
TARGET = useStaticLib
INCLUDEPATH += "simpleStaticLibrary/include"
LIBS += -L../simpleStaticLibrary/lib -lsimpleStaticLibrary
QT += gui widgets

SOURCES += src/main.cpp
