######################################################################
# Automatically generated by qmake (3.0) Thu Oct 11 10:59:18 2018
######################################################################

TEMPLATE = app
TARGET = analogueClock
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += main.cpp
