######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 5 23:27:24 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
