######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 7 19:04:44 2018
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestQString.hpp
SOURCES += TestQString.cpp
