######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 6 00:03:10 2018
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestQString.hpp
SOURCES += TestQString.cpp
