######################################################################
# Automatically generated by qmake (3.0) Thu Oct 11 10:59:18 2018
######################################################################

TEMPLATE = app
TARGET = useSharedLib
INCLUDEPATH += simpleSharedLibrary/include
LIBS += -L../simpleSharedLibrary/lib -lsimpleSharedLibrary
QT += gui widgets

SOURCES += src/main.cpp
