######################################################################
# Automatically generated by qmake (3.0) Thu Oct 11 11:46:32 2018
######################################################################

TEMPLATE = app
TARGET = simpleLibrary
INCLUDEPATH += .
QT += gui widgets

# Input
HEADERS += MyMainWindow.hpp
SOURCES += MyMainWindow.cpp
