######################################################################
# Automatically generated by qmake (3.0) Mon Aug 7 17:26:00 2017
######################################################################

TEMPLATE = app
TARGET = transform
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += transform.cpp
